### ISSUE TITLE
Update for OpenACC 3.0?

### ISSUE THREAD

**Issue by clementval** [OpenACCUserGroup/OpenACCV-V#6]
Last update was done before the released of OpenACC 3.0. Is there an update coming to check newest implementation?

**Comment by utimatu** [comment]
Right now, I'm in the middle of a major update to the structure of the test suite, along with some other fixes and new tests. I think that should be rolling out early next year, and once that is released, I'll be focusing on updating the tests to have better coverage of both 2.7 and 3.0.

**Comment by dmitry-dm-kozlov** [comment]
> Right now, I'm in the middle of a major update to the structure of the test suite, along with some other fixes and new tests. I think that should be rolling out early next year, and once that is released, I'll be focusing on updating the tests to have better coverage of both 2.7 and 3.0.

Hi Kyle,
any news on that?

**Comment by clementval** [comment]
3.1 is coming soon so it would be nice to have some news on this.

**Comment by ajarmusch** [comment]
Hi,
Our team is constantly updating. We will start using the GitHub milestones to track our progress of compliance to the spec. You can also visit our [website](https://crpl.cis.udel.edu/oaccvv/) for more information. 

If there is anything else I can assist with, please let me know and I will be happy to help.
