### ISSUE TITLE
Copyin clause with library call syntax in acc_delete_async.f90 and acc_delete_async_with_len.f90

### ISSUE THREAD

**Issue by clementval** [OpenACCUserGroup/OpenACCV-V#7]
The call here seems not correct according to the specification. 

https://github.com/OpenACCUserGroup/OpenACCV-V/blob/631141738b5932016ebc38e586e75a2b4f1487ac/Tests/acc_delete_async.f90#L74

The library has a `acc_copyin(a, len)` signature but the clause accept normally a `var-list`

Same in this test `acc_delete_async_with_len.f90`

https://github.com/OpenACCUserGroup/OpenACCV-V/blob/631141738b5932016ebc38e586e75a2b4f1487ac/Tests/acc_delete_async_with_len.f90#L72

**Comment by utimatu** [comment]
Thanks for pointing this out.  I'm not able to fix it now, but I'll send out an update next week.

**Comment by clementval** [comment]
@utimatu Thanks for the quick fix during the holidays!
